export enum ErrorCodes {
  TRANSACTION_VALIDATION_ERROR = 'TRANSACTION_VALIDATION_ERROR',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',

  AMOUNT_REQUIRED = 'AMOUNT_REQUIRED',
  AMOUNT_INVALID = 'AMOUNT_INVALID',
  AMOUNT_NOT_FINITE = 'AMOUNT_NOT_FINITE',
  AMOUNT_NEGATIVE = 'AMOUNT_NEGATIVE',
  AMOUNT_TOO_MANY_DECIMALS = 'AMOUNT_TOO_MANY_DECIMALS',
  TIMESTAMP_REQUIRED = 'TIMESTAMP_REQUIRED',
  TIMESTAMP_INVALID_TYPE = 'TIMESTAMP_INVALID_TYPE',
  TIMESTAMP_INVALID = 'TIMESTAMP_INVALID',
  TIMESTAMP_FUTURE = 'TIMESTAMP_FUTURE',
  TIMESTAMP_STRING_INVALID = 'TIMESTAMP_STRING_INVALID',

  DOMAIN_VALIDATION_ERROR = 'DOMAIN_VALIDATION_ERROR',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
